---

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - python-psycopg2
    - postgresql-server

- name: Initialize postgresql
  command: postgresql-setup initdb creates=/var/lib/pgsql/data/postgresql.conf

- name: Enable and start postgresql
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Listen on all interfaces
  lineinfile:
    dest: /var/lib/pgsql/data/postgresql.conf
    state: present
    regexp: "^#?listen_addresses ="
    line: "listen_addresses = '*'"
  notify: Restart postgres

- name: Allow external connections via pg_hba
  lineinfile:
    dest: /var/lib/pgsql/data/pg_hba.conf
    line: host all  all 172.0.0.0/8 md5
  notify: Restart postgres

- block:
  - name: create postgresql users
    postgresql_user:
      name: "{{ item.key }}"
      password: "{{ item.value }}"
      encrypted: yes
    loop: "{{ q('dict', postgresql_users) }}"
    loop_control:
      label: "{{ item.key }}"

  - name: create postgresql user databases
    postgresql_db:
      name: "{{ item.key }}"
      owner: "{{ item.key }}"
    loop: "{{ q('dict', postgresql_users) }}"
    loop_control:
      label: "{{ item.key }}"

  become: yes
  become_user: postgres
